app_port: 8000
djangoservice:
    user_dir: "/home/belli"
    group: "belli"
    workingdir: {{user_dir}}/django-project/movies_app
    execstart: {{user_dir}}/django-project/myvenv/bin/gunicorn --access-logfile - --workers 3 --bind 0.0.0.0:8000 movies_app.wsgi:application

vars_files:
  - secrets/django-secret-key.yml

django:
    env:
        SECRET_KEY: "{{ DJ_SECRET_KEY }}"
        DATABASE_URL: 'sqlite:///./db.sqlite3'
        ALLOWED_HOSTS: '127.0.0.1,localhost'
        EMAIL_USER: 'devops.mailing.71.110@gmail.com'
        EMAIL_PASSWD: ''