app_port: 8000
djangoservice:
    user_dir: "/home/azureuser"
    group: "azureuser"
    workingdir: "{{ user_dir }}/django-project/movies_app"
    execstart: "{{user_dir}}/django-project/myvenv/bin/gunicorn --access-logfile - --workers 3 --bind 0.0.0.0:8000 movies_app.wsgi:application"
