---
gcloud_ansible:
    hosts:
        ansible-vm:
            ansible_host: ansible-vm
azure_docker:
    hosts:
        docker-vm:
            ansible_host: docker-vm
test:
    hosts:
        deployment1:
            ansible_host: deployment1