---
gcloud_ansible:
    hosts:
        ansible-vm:
            ansible_host: movies.ans.bellias.cloudns.cl
            ansible_port: 22
            ansible_ssh_user: belli
        ansible-vm-2:
            ansible_host: ansible.jenkins.cloudns.cl
            ansible_port: 22
            ansible_ssh_user: it218110
gcloud_docker:
    hosts:
        docker-vm:
            ansible_host: movies.dock.bellias.cloudns.cl
            ansible_port: 22
            ansible_ssh_user: azureuser
        docker-vm-2:
            ansible_host: movies-docker.jenkins.cloudns.cl
            ansible_port: 22
            ansible_ssh_user: azureuser
test:
    hosts:
        deployment1
jenkins:
    hosts:
        jenkins-server:
            ansible_host: jenkins.bellias.cloudns.cl
            ansible_port: 22
            ansible_ssh_user: belli