---
gcloud_ansible:
    hosts:
        ansible-vm:
            ansible_host: movies.ans.bellias.cloudns.cl
            ansible_port: 22
            ansible_ssh_user: belli
azure_docker:
    hosts:
        docker-vm:
            ansible_host: movies.dock.bellias.cloudns.cl
            ansible_port: 22
            ansible_ssh_user: azureuser
test:
    hosts:
        deployment1 #:
            #ansible_host: django.bellias.cloudns.cl
            #ansible_port: 22
            #ansible_ssh_user: azureuser

jenkins:
    hosts:
        jenkins-server:
            ansible_host: jenkins.bellias.cloudns.cl
            ansible_port: 22
            ansible_ssh_user: belli