---
- name: populate k8s env vars
  hosts: localhost

  vars:
    user_dir: "/var/lib/jenkins/workspace"
    app_dir: "{{user_dir}}/e-movies-app"

  tasks:
  - name: copy env file
    shell: "cp {{app_dir}}/movies_app/movies_app/.env.example {{app_dir}}/movies_app/movies_app/.env"

  - name: populate ~/.env secret key
    lineinfile:
        dest: "{{app_dir}}/movies_app/movies_app/.env"
        state: present
        regexp: "^SECRET_KEY="
        line: "SECRET_KEY={{SECRET_KEY}}"

  - name: populate ~/.env db url
    lineinfile:
        dest: "{{app_dir}}/movies_app/movies_app/.env"
        state: present
        regexp: "^DATABASE_URL="
        line: "DATABASE_URL={{DATABASE_URL}}"

  - name: populate ~/.env allowed hosts
    lineinfile:
        dest: "{{app_dir}}/movies_app/movies_app/.env"
        state: present
        regexp: "^ALLOWED_HOSTS="
        line: "ALLOWED_HOSTS={{ALLOWED_HOSTS}}"

  - name: populate ~/.env email user
    lineinfile:
        dest: "{{app_dir}}/movies_app/movies_app/.env"
        state: present
        regexp: "^EMAIL_USER="
        line: "EMAIL_USER={{EMAIL_USER}}"

  - name: populate ~/.env email pass
    lineinfile:
        dest: "{{app_dir}}/movies_app/movies_app/.env"
        state: present
        regexp: "^EMAIL_PASSWD="
        line: "EMAIL_PASSWD={{EMAIL_PASSWD}}"

  - name: populate ~/.env debug var
    lineinfile:
        dest: "{{app_dir}}/movies_app/movies_app/.env"
        state: present
        regexp: "^DEBUG="
        line: "DEBUG=False"

  - name: populate fqdn in ingress http controller
    lineinfile:
        dest: "{{app_dir}}/k8s/django/django-ingress.yaml"
        state: present
        regexp: "^  - host"
        line: '  - host: "{{ALLOWED_HOSTS}}"'

  - name: populate fqdn in ingress https controller spot 1
    lineinfile:
        dest: "{{app_dir}}/k8s/django/django-https-ingress.yaml"
        state: present
        regexp: "^  - host"
        line: '  - host: "{{ALLOWED_HOSTS}}"'

  - name: populate fqdn in ingress https controller spot 2
    lineinfile:
        dest: "{{app_dir}}/k8s/django/django-https-ingress.yaml"
        state: present
        regexp: "^    - hosts: "
        line: '    - hosts: \n      - {{ALLOWED_HOSTS}}'