---
- name: populate k8s env vars
  hosts: localhost

  vars:
    user_dir: "/var/lib/jenkins/workspace"
    app_dir: "{{user_dir}}/e-movies-app"

  tasks:
  - name: copy env file
    shell: "cp {{app_dir}}/movies_app/movies_app/.env.example {{app_dir}}/movies_app/movies_app/.env"

  - name: populate ~/.env secret key
    lineinfile:
        dest: "{{app_dir}}/movies_app/movies_app/.env"
        state: present
        regexp: "^SECRET_KEY="
        line: "SECRET_KEY={{SECRET_KEY}}"

  - name: populate ~/.env db url
    lineinfile:
        dest: "{{app_dir}}/movies_app/movies_app/.env"
        state: present
        regexp: "^DATABASE_URL="
        line: "DATABASE_URL={{DATABASE_URL}}"

  - name: populate ~/.env allowed hosts
    lineinfile:
        dest: "{{app_dir}}/movies_app/movies_app/.env"
        state: present
        regexp: "^ALLOWED_HOSTS="
        line: "ALLOWED_HOSTS={{ALLOWED_HOSTS}}"
        
  - name: populate ~/.env debug var
    lineinfile:
        dest: "{{app_dir}}/movies_app/movies_app/.env"
        state: present
        regexp: "^DEBUG="
        line: "DEBUG=False"