---
- hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
  - secrets/django-secret-key.yml

  tasks:
  - name: Echo the django secret key which was injected into the env
    shell: echo "{{ DJ_SECRET_KEY }}"
    register: echo_result

  - name: Show the result.
    debug: var=echo_result.stdout